### PR TITLE
fixes os_type errors

### PR DESCRIPTION
**Pull request by uk-james**
Simple fix for change letters case

Also related to issue #31 

fixes below error:

```
╷
│ Error: expected os_type to be one of [Windows Linux], got linux
│
│   with module.aci-devops-agent.azurerm_container_group.linux-container-group,
│   on .terraform\modules\aci-devops-agent\main.tf line 55, in resource "azurerm_container_group" "linux-container-group":
│   55:   os_type             = "linux"
│
╵
╷
│ Error: expected os_type to be one of [Windows Linux], got windows
│
│   with module.aci-devops-agent.azurerm_container_group.windows-container-group,

│   on .terraform\modules\aci-devops-agent\main.tf line 141, in resource "azurerm_container_group" "windows-container-group":
```

### CODE REVIEW

**Comment by jcorioland** [comment]
@uk-james thanks for your contribution. I cannot see any change in your commit. Can you please double check?

**Comment by clbarrett** [comment]
Any ETA on this fix?  I'm encountering the same errors.

**Comment by clbarrett** [comment]
image

For some odd reason, in all versions 0.9.0, 0.9.1, & 0.9.2 the main.tf has a lower case linux & windows.  Yet that isn't what I see in the code on master.  How odd.

**Comment by jcorioland** [comment]
@clbarrett are you running the `terraform plan` command from a Windows machine or from a unix-like shell? I am trying to reproduce the issue.

**Comment by jcorioland** [comment]
OK, so actually the update has already been merged (#32), but new release was not done. I just did it and it fixes the issue for me to switch to version [0.9.3](https://registry.terraform.io/modules/Azure/aci-devops-agent/azurerm/0.9.3). @clbarret @uk-james can you confirm that it solves the issue, please?

**Comment by uk-james** [comment]
@jcorioland sorry for the delay! I did miss it you're right, i'll hold off until @clbarrett confirms, if all is ok, i'll go ahead and close this PR.

**Comment by clbarrett** [comment]
Yes, was reproducing this on a Windows machine using Git-Bash if it matters.  Version 0.9.3 fixed the problem (and one other subsequent one).  Thanks for the speedy response!

**Pull request closed without merging**
