### PR TITLE
allow modification of container port

### PR DESCRIPTION
**Pull request by kathryn-explorable**
Thanks for this useful module!
It would be nice to allow modification of the container port. Flask apps require 5000 by default. Or 443 would be useful for other applications.

### CODE REVIEW

**Comment by jcorioland** [comment]
Hi @kathryn-explorable! thanks for the PR (and sorry for the delay). Why exactly you need to run flask inside the Azure DevOps agent image?

**Comment by kathryn-explorable** [comment]
Hi @jcorioland the plan was to create a serverless Flask API. Python has many data science libraries, and it's usually what I use for bioinformatics applications. If you think there's a better approach for this sort of thing, I'm happy to get advice!

**Comment by jcorioland** [comment]
Hi @kathryn-explorable, thanks for the update, but I am not sure to understand exactly what you are trying to achieve. Why running the Flask API into the same container than the Azure DevOps agent?
Have you thought to run it into a dedicated container instance? Something like that -> https://medium.com/@alexjsanchez/creating-and-deploying-a-flask-app-with-docker-on-azure-in-5-easy-9f7aa7a12145
?

**Comment by jcorioland** [comment]
@kathryn-explorable have you been able to solve your issue? Should we keep this PR open?

**Comment by jcorioland** [comment]
Closing this PR as it was not active since June.
Feel free to reopen @kathryn-explorable and provide more details, if needed.

**Pull request closed without merging**
